package es.uniovi.reflection.graph.models;

public enum GraphPropertyTypes {
    INTEGER, FLOAT, BOOLEAN, STRING, DATE, TIME, DATETIME, LOCALTIME,
    LOCALDATETIME, DURATION, POINTCAR, POINTCAR3D, POINTWGS, POINTWGS3D,
    ARRAYINTEGER, ARRAYFLOAT, ARRAYBOOLEAN, ARRAYSTRING, ARRAYDATE, ARRAYTIME, ARRAYDATETIME, ARRAYLOCALTIME,
    ARRAYLOCALDATETIME, ARRAYDURATION, ARRAYPOINTCAR, ARRAYPOINTCAR3D, ARRAYPOINTWGS, ARRAYPOINTWGS3D
}
